esphome:
  name: esphome-vask
  min_version: 2024.11.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.f_cpu: 160000000L #increase clock speed

esp8266:
  board: d1_mini  # Adjust to your specific ESP8266 board

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "Ventaxia Fallback"
    password: !secret fallback_password

captive_portal:

external_components:
  - source: ../components
  # - source: github://alextrical/ESPHome-Vent-Axia-Sentinel-Kinetic/@latest
  #   components: [ vent_axia_sentinel_kinetic ]
  #   refresh: always

logger:
  level: DEBUG
  baud_rate: 0

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  id: vask_uart

i2c:
  sda: 4
  scl: 5
  scan: false
  
display:
  - platform: lcd_pcf8574
    id: lcd
    dimensions: 16x2
    address: 0x27
    update_interval: 300ms
    lambda: |-
        it.printf(0, 0, "%s", id(line1).state.c_str());
        it.printf(0, 1, "%s", id(line2).state.c_str());

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      mode:
        input: true
        pullup: true
      inverted: true
    id: upsw
    entity_category: "diagnostic"
    on_press:
      then:
        - switch.turn_on: sw_up
    on_release:
      then:
        - switch.turn_off: sw_up
  - platform: gpio
    pin:
      number: 12
      mode:
        input: true
        pullup: true
      inverted: true
    id: downsw
    entity_category: "diagnostic"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - switch.turn_on: sw_down
    on_release:
      - switch.turn_off: sw_down
  - platform: gpio
    pin:
      number: 14
      mode:
        input: true
        pullup: true
      inverted: true
    id: setsw
    entity_category: "diagnostic"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - switch.turn_on: sw_set
    on_release:
      - switch.turn_off: sw_set
  - platform: gpio
    pin:
      number: 13
      mode:
        input: true
        pullup: true
      inverted: true
    id: mainsw
    entity_category: "diagnostic"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - switch.turn_on: sw_main
    on_release:
      - switch.turn_off: sw_main

switch:
  - platform: vent_axia_sentinel_kinetic
    up:
      name: "Up Switch"
      id: sw_up
    down:
      name: "Down Switch"
      id: sw_down
    set:
      name: "Set Switch"
      id: sw_set
    main:
      name: "Main Switch"
      id: sw_main

vent_axia_sentinel_kinetic:
  - id: vask
    uart_id: vask_uart
    diagnostic_button:
      id: diagnostic_button
      name: "Fetch Diagnostic"
    line1:
      id: line1
      name: "Line 1"
    line2:
      id: line2
      name: "Line 2"
    diagnostic0:
      name: "Diagnostic 0"
      entity_category: "diagnostic"
    diagnostic1:
      name: "Diagnostic 1"
      entity_category: "diagnostic"
    diagnostic2:
      name: "Diagnostic 2"
      entity_category: "diagnostic"
    diagnostic3:
      name: "Diagnostic 3"
      entity_category: "diagnostic"
    diagnostic4:
      name: "Diagnostic 4"
      entity_category: "diagnostic"
    diagnostic5:
      name: "Diagnostic 5"
      entity_category: "diagnostic"
    diagnostic6:
      name: "Diagnostic 6"
      entity_category: "diagnostic"
    diagnostic7:
      name: "Diagnostic 7"
      entity_category: "diagnostic"
    diagnostic8:
      name: "Diagnostic 8"
      entity_category: "diagnostic"
    diagnostic9:
      name: "Diagnostic 9"
      entity_category: "diagnostic"
    diagnostic10:
      name: "Diagnostic 10"
      entity_category: "diagnostic"
    diagnostic11:
      name: "Diagnostic 11"
      entity_category: "diagnostic"
    diagnostic12:
      name: "Diagnostic 12"
      entity_category: "diagnostic"
    diagnostic13:
      name: "Diagnostic 13"
      entity_category: "diagnostic"
    diagnostic14:
      name: "Diagnostic 14"
      entity_category: "diagnostic"
    diagnostic15:
      name: "Diagnostic 15"
      entity_category: "diagnostic"
    diagnostic16:
      name: "Diagnostic 16"
      entity_category: "diagnostic"
    diagnostic17:
      name: "Diagnostic 17"
      entity_category: "diagnostic"
    diagnostic18:
      name: "Diagnostic 18"
      entity_category: "diagnostic"
    diagnostic19:
      name: "Diagnostic 19"
      entity_category: "diagnostic"
    diagnostic20:
      name: "Diagnostic 20"
      entity_category: "diagnostic"
    diagnostic21:
      name: "Diagnostic 21"
      entity_category: "diagnostic"
    diagnostic22:
      name: "Diagnostic 22"
      entity_category: "diagnostic"
    diagnostic23:
      name: "Diagnostic 23"
      entity_category: "diagnostic"
    diagnostic24:
      name: "Diagnostic 24"
      entity_category: "diagnostic"
    diagnostic25:
      name: "Diagnostic 25"
      entity_category: "diagnostic"
    diagnostic26:
      name: "Diagnostic 26"
      entity_category: "diagnostic"
    diagnostic27:
      name: "Diagnostic 27"
      entity_category: "diagnostic"
    diagnostic28:
      name: "Diagnostic 28"
      entity_category: "diagnostic"